import { optionType } from "./OptionType";

export const WeaponOption = [
  "none",
  "str",
  "dex",
  "int",
  "luk",
  "gongper",
  "maper",
  "criprob",
  "damage",
  "allstat",
  "gong",
  "ma",
  "ignoredef",
  "bossdamage",
];

export const Weapon: optionType[] = [
  { type: "red", order: "first", name: "str", value: 12, prob: 0.097561 },
  { type: "red", order: "first", name: "dex", value: 12, prob: 0.097561 },
  { type: "red", order: "first", name: "int", value: 12, prob: 0.097561 },
  { type: "red", order: "first", name: "luk", value: 12, prob: 0.097561 },
  { type: "red", order: "first", name: "gongper", value: 12, prob: 0.04878 },
  { type: "red", order: "first", name: "maper", value: 12, prob: 0.04878 },
  { type: "red", order: "first", name: "criprob", value: 12, prob: 0.04878 },
  { type: "red", order: "first", name: "damage", value: 12, prob: 0.04878 },
  { type: "red", order: "first", name: "allstat", value: 9, prob: 0.073171 },
  { type: "red", order: "first", name: "gong", value: 32, prob: 0.04878 },
  { type: "red", order: "first", name: "ma", value: 32, prob: 0.04878 },
  {
    type: "red",
    order: "first",
    name: "ignoredef",
    value: 35,
    prob: 0.04878,
    options: "multi",
  },
  {
    type: "red",
    order: "first",
    name: "ignoredef",
    value: 40,
    prob: 0.04878,
    options: "multi",
  },
  {
    type: "red",
    order: "first",
    name: "bossdamage",
    value: 35,
    prob: 0.097561,
  },
  { type: "red", order: "first", name: "bossdamage", value: 40, prob: 0.04878 },
  { type: "red", order: "second", name: "str", value: 9, prob: 0.104651 },
  { type: "red", order: "second", name: "dex", value: 9, prob: 0.104651 },
  { type: "red", order: "second", name: "int", value: 9, prob: 0.104651 },
  { type: "red", order: "second", name: "luk", value: 9, prob: 0.104651 },
  { type: "red", order: "second", name: "gongper", value: 9, prob: 0.062791 },
  { type: "red", order: "second", name: "maper", value: 9, prob: 0.062791 },
  { type: "red", order: "second", name: "criprob", value: 9, prob: 0.083721 },
  { type: "red", order: "second", name: "damage", value: 9, prob: 0.062791 },
  { type: "red", order: "second", name: "allstat", value: 6, prob: 0.083721 },
  {
    type: "red",
    order: "second",
    name: "ignoredef",
    value: 30,
    prob: 0.062791,
    options: "multi",
  },
  {
    type: "red",
    order: "second",
    name: "bossdamage",
    value: 30,
    prob: 0.062791,
  },
  { type: "red", order: "second", name: "str", value: 12, prob: 0.009756 },
  { type: "red", order: "second", name: "dex", value: 12, prob: 0.009756 },
  { type: "red", order: "second", name: "int", value: 12, prob: 0.009756 },
  { type: "red", order: "second", name: "luk", value: 12, prob: 0.009756 },
  { type: "red", order: "second", name: "gongper", value: 12, prob: 0.004878 },
  { type: "red", order: "second", name: "maper", value: 12, prob: 0.004878 },
  { type: "red", order: "second", name: "criprob", value: 12, prob: 0.004878 },
  { type: "red", order: "second", name: "damage", value: 12, prob: 0.004878 },
  { type: "red", order: "second", name: "allstat", value: 9, prob: 0.007317 },
  { type: "red", order: "second", name: "gong", value: 32, prob: 0.004878 },
  { type: "red", order: "second", name: "ma", value: 32, prob: 0.004878 },
  {
    type: "red",
    order: "second",
    name: "ignoredef",
    value: 35,
    prob: 0.004878,
    options: "multi",
  },
  {
    type: "red",
    order: "second",
    name: "ignoredef",
    value: 40,
    prob: 0.004878,
    options: "multi",
  },
  {
    type: "red",
    order: "second",
    name: "bossdamage",
    value: 35,
    prob: 0.009756,
  },
  {
    type: "red",
    order: "second",
    name: "bossdamage",
    value: 40,
    prob: 0.004878,
  },
  { type: "red", order: "third", name: "str", value: 9, prob: 0.115116 },
  { type: "red", order: "third", name: "dex", value: 9, prob: 0.115116 },
  { type: "red", order: "third", name: "int", value: 9, prob: 0.115116 },
  { type: "red", order: "third", name: "luk", value: 9, prob: 0.115116 },
  { type: "red", order: "third", name: "gongper", value: 9, prob: 0.06907 },
  { type: "red", order: "third", name: "maper", value: 9, prob: 0.06907 },
  { type: "red", order: "third", name: "criprob", value: 9, prob: 0.092093 },
  { type: "red", order: "third", name: "damage", value: 9, prob: 0.06907 },
  { type: "red", order: "third", name: "allstat", value: 6, prob: 0.092093 },
  {
    type: "red",
    order: "third",
    name: "ignoredef",
    value: 30,
    prob: 0.06907,
    options: "multi",
  },
  { type: "red", order: "third", name: "bossdamage", value: 30, prob: 0.06907 },
  { type: "red", order: "third", name: "str", value: 12, prob: 0.000976 },
  { type: "red", order: "third", name: "dex", value: 12, prob: 0.000976 },
  { type: "red", order: "third", name: "int", value: 12, prob: 0.000976 },
  { type: "red", order: "third", name: "luk", value: 12, prob: 0.000976 },
  { type: "red", order: "third", name: "gongper", value: 12, prob: 0.000488 },
  { type: "red", order: "third", name: "maper", value: 12, prob: 0.000488 },
  { type: "red", order: "third", name: "criprob", value: 12, prob: 0.000488 },
  { type: "red", order: "third", name: "damage", value: 12, prob: 0.000488 },
  { type: "red", order: "third", name: "allstat", value: 9, prob: 0.000732 },
  { type: "red", order: "third", name: "gong", value: 32, prob: 0.000488 },
  { type: "red", order: "third", name: "ma", value: 32, prob: 0.000488 },
  {
    type: "red",
    order: "third",
    name: "ignoredef",
    value: 35,
    prob: 0.000488,
    options: "multi",
  },
  {
    type: "red",
    order: "third",
    name: "ignoredef",
    value: 40,
    prob: 0.000488,
    options: "multi",
  },
  {
    type: "red",
    order: "third",
    name: "bossdamage",
    value: 35,
    prob: 0.000976,
  },
  {
    type: "red",
    order: "third",
    name: "bossdamage",
    value: 40,
    prob: 0.000488,
  },
  { type: "black", order: "first", name: "str", value: 12, prob: 0.097561 },
  { type: "black", order: "first", name: "dex", value: 12, prob: 0.097561 },
  { type: "black", order: "first", name: "int", value: 12, prob: 0.097561 },
  { type: "black", order: "first", name: "luk", value: 12, prob: 0.097561 },
  { type: "black", order: "first", name: "gongper", value: 12, prob: 0.04878 },
  { type: "black", order: "first", name: "maper", value: 12, prob: 0.04878 },
  { type: "black", order: "first", name: "criprob", value: 12, prob: 0.04878 },
  { type: "black", order: "first", name: "damage", value: 12, prob: 0.04878 },
  { type: "black", order: "first", name: "allstat", value: 9, prob: 0.073171 },
  { type: "black", order: "first", name: "gong", value: 32, prob: 0.04878 },
  { type: "black", order: "first", name: "ma", value: 32, prob: 0.04878 },
  {
    type: "black",
    order: "first",
    name: "ignoredef",
    value: 35,
    prob: 0.04878,
    options: "multi",
  },
  {
    type: "black",
    order: "first",
    name: "ignoredef",
    value: 40,
    prob: 0.04878,
    options: "multi",
  },
  {
    type: "black",
    order: "first",
    name: "bossdamage",
    value: 35,
    prob: 0.097561,
  },
  {
    type: "black",
    order: "first",
    name: "bossdamage",
    value: 40,
    prob: 0.04878,
  },
  { type: "black", order: "second", name: "str", value: 9, prob: 0.093023 },
  { type: "black", order: "second", name: "dex", value: 9, prob: 0.093023 },
  { type: "black", order: "second", name: "int", value: 9, prob: 0.093023 },
  { type: "black", order: "second", name: "luk", value: 9, prob: 0.093023 },
  { type: "black", order: "second", name: "gongper", value: 9, prob: 0.055814 },
  { type: "black", order: "second", name: "maper", value: 9, prob: 0.055814 },
  { type: "black", order: "second", name: "criprob", value: 9, prob: 0.074419 },
  { type: "black", order: "second", name: "damage", value: 9, prob: 0.055814 },
  { type: "black", order: "second", name: "allstat", value: 6, prob: 0.074419 },
  {
    type: "black",
    order: "second",
    name: "ignoredef",
    value: 30,
    prob: 0.055814,
    options: "multi",
  },
  {
    type: "black",
    order: "second",
    name: "bossdamage",
    value: 30,
    prob: 0.055814,
  },
  { type: "black", order: "second", name: "str", value: 12, prob: 0.019512 },
  { type: "black", order: "second", name: "dex", value: 12, prob: 0.019512 },
  { type: "black", order: "second", name: "int", value: 12, prob: 0.019512 },
  { type: "black", order: "second", name: "luk", value: 12, prob: 0.019512 },
  {
    type: "black",
    order: "second",
    name: "gongper",
    value: 12,
    prob: 0.009756,
  },
  { type: "black", order: "second", name: "maper", value: 12, prob: 0.009756 },
  {
    type: "black",
    order: "second",
    name: "criprob",
    value: 12,
    prob: 0.009756,
  },
  { type: "black", order: "second", name: "damage", value: 12, prob: 0.009756 },
  { type: "black", order: "second", name: "allstat", value: 9, prob: 0.014634 },
  { type: "black", order: "second", name: "gong", value: 32, prob: 0.009756 },
  { type: "black", order: "second", name: "ma", value: 32, prob: 0.009756 },
  {
    type: "black",
    order: "second",
    name: "ignoredef",
    value: 35,
    prob: 0.009756,
    options: "multi",
  },
  {
    type: "black",
    order: "second",
    name: "ignoredef",
    value: 40,
    prob: 0.009756,
    options: "multi",
  },
  {
    type: "black",
    order: "second",
    name: "bossdamage",
    value: 35,
    prob: 0.019512,
  },
  {
    type: "black",
    order: "second",
    name: "bossdamage",
    value: 40,
    prob: 0.009756,
  },
  { type: "black", order: "third", name: "str", value: 9, prob: 0.110465 },
  { type: "black", order: "third", name: "dex", value: 9, prob: 0.110465 },
  { type: "black", order: "third", name: "int", value: 9, prob: 0.110465 },
  { type: "black", order: "third", name: "luk", value: 9, prob: 0.110465 },
  { type: "black", order: "third", name: "gongper", value: 9, prob: 0.066279 },
  { type: "black", order: "third", name: "maper", value: 9, prob: 0.066279 },
  { type: "black", order: "third", name: "criprob", value: 9, prob: 0.088372 },
  { type: "black", order: "third", name: "damage", value: 9, prob: 0.066279 },
  { type: "black", order: "third", name: "allstat", value: 6, prob: 0.088372 },
  {
    type: "black",
    order: "third",
    name: "ignoredef",
    value: 30,
    prob: 0.066279,
    options: "multi",
  },
  {
    type: "black",
    order: "third",
    name: "bossdamage",
    value: 30,
    prob: 0.066279,
  },
  { type: "black", order: "third", name: "str", value: 12, prob: 0.004878 },
  { type: "black", order: "third", name: "dex", value: 12, prob: 0.004878 },
  { type: "black", order: "third", name: "int", value: 12, prob: 0.004878 },
  { type: "black", order: "third", name: "luk", value: 12, prob: 0.004878 },
  { type: "black", order: "third", name: "gongper", value: 12, prob: 0.002439 },
  { type: "black", order: "third", name: "maper", value: 12, prob: 0.002439 },
  { type: "black", order: "third", name: "criprob", value: 12, prob: 0.002439 },
  { type: "black", order: "third", name: "damage", value: 12, prob: 0.002439 },
  { type: "black", order: "third", name: "allstat", value: 9, prob: 0.003659 },
  { type: "black", order: "third", name: "gong", value: 32, prob: 0.002439 },
  { type: "black", order: "third", name: "ma", value: 32, prob: 0.002439 },
  {
    type: "black",
    order: "third",
    name: "ignoredef",
    value: 35,
    prob: 0.002439,
    options: "multi",
  },
  {
    type: "black",
    order: "third",
    name: "ignoredef",
    value: 40,
    prob: 0.002439,
    options: "multi",
  },
  {
    type: "black",
    order: "third",
    name: "bossdamage",
    value: 35,
    prob: 0.004878,
  },
  {
    type: "black",
    order: "third",
    name: "bossdamage",
    value: 40,
    prob: 0.002439,
  },
];
